# What is numpy?

From the [documentation](https://docs.scipy.org/doc/numpy/user/whatisnumpy.html): NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object and an assortment of routines for fast operations on arrays.


At the core of the NumPy package, is the `ndarray` object. This encapsulates n-dimensional arrays of homogeneous data types, with many operations being performed in compiled code for performance. There are several important differences between NumPy arrays and the standard Python sequences:

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.
- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory. 
- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.
- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays. In other words, in order to efficiently use much (perhaps even most) of today’s scientific/mathematical Python-based software, just knowing how to use Python’s built-in sequence types is insufficient - one also needs to know how to use NumPy arrays.





The points about sequence size and speed are particularly important in scientific computing. As a simple example, consider the below function written using pure python that computes the dot product of two vectors.

In [0]:
def dot_product(a,b):
    dot_prod = 0
    for i in range(len(a)):
        dot_prod += a[i]*b[i]
    
    return dot_prod


In [0]:
a = [1,2,3]

dot_product(a,a)

14

Numpy has a function for dot product: [np.dot](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html)

In [0]:
import numpy as np

a = np.array([1,2,3])

np.dot(a,a)

14

In [0]:
very_large_vector = np.random.randn(1000000)

In [0]:
type(very_large_vector)

numpy.ndarray

In [0]:
import timeit

start_time = timeit.default_timer()

dot_product(very_large_vector, very_large_vector)

print(timeit.default_timer() - start_time)


0.4823522340002455


In [0]:
start_time = timeit.default_timer()

np.dot(very_large_vector, very_large_vector)

print(timeit.default_timer() - start_time)

0.007956564999403781


As you can see above, `np.dot` function is much faster than the `dot_product` function we implemented. 

# Basics

NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. NumPy’s array class is called `ndarray`. It is also known by the alias `array`.

In NumPy, dimensions are called axes. For example, the array `[1, 2, 1]` has one axis. That axis has 3 elements in it, so we say it has a length of 3. 

In [0]:
# You can create arrays by passing a Python list or tuple into the `np.array()` function
a = np.array([1,2,3])
print(a)
# The number of axes (dimensions) of the array.
a.ndim

[1 2 3]


1

In [0]:
# The dimensions of the array. This is a tuple of integers indicating the size of 
# the array in each dimension. For a matrix with n rows and m columns, shape will 
# be (n,m). The length of the shape tuple is therefore the number of axes, ndim.
a.shape

(3,)

In [0]:
# The type of the elements in the array.
a.dtype

dtype('int64')

In [0]:
a = np.array([[1,2,3], [4,5,6]])

print(a)

[[1 2 3]
 [4 5 6]]


In [0]:
a.ndim

2

In [0]:
a.shape

(2, 3)

Numpy provides some handy functions to create arrrays with preset values that you can change later:
 - [np.zeros](https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html)
 - [np.ones](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)
 - [np.arrange](https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html)
 - [np.linspace](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linspace.html)



In [0]:
arr1 = np.zeros(3)
print(arr1)

[0. 0. 0.]


In [0]:
arr2 = np.zeros((2,3))
print(arr2)

[[0. 0. 0.]
 [0. 0. 0.]]


In [0]:
arr3 = np.ones((3,4))
print(arr3)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Arithmetic operations on arrays apply elementwise.

In [0]:
a = np.array([0,1,2,3])
b = np.array([4,4,4,4])

In [0]:
b-a

array([4, 3, 2, 1])

In [0]:
a*b

array([ 0,  4,  8, 12])

This wouldn't work with Python lists. 

In [0]:
lst1 = [0,1,2,3]
lst2 = [4,4,4,4]

In [0]:
lst1 * lst2

TypeError: ignored

In [0]:
# Broadcasting: 
5 * a

array([ 0,  5, 10, 15])

In [0]:
# This does not work in Python
5 * lst1 #concatenate lst1 to itself 5 times. 

[0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]

Matrix multiplication is done by [np.matmul](https://docs.scipy.org/doc/numpy/reference/generated/numpy.matmul.html#numpy.matmul) function.

In [0]:
A = np.random.rand(3,4)
print(A)

[[0.25899609 0.14145729 0.0580489  0.52287064]
 [0.48992194 0.95913996 0.80004958 0.18508451]
 [0.78293266 0.29994257 0.75530892 0.19192985]]


In [0]:
B = np.random.rand(4,6)
print(B)

[[0.90015307 0.54280879 0.47566129 0.59992476 0.32389524 0.21983577]
 [0.72397575 0.3978631  0.06083471 0.37057479 0.3801838  0.31151261]
 [0.72601481 0.07734013 0.14991535 0.65992103 0.34835594 0.70795353]
 [0.21576661 0.43015131 0.0035572  0.49164829 0.82701971 0.08088041]]


In [0]:
# This tries to multiply element-wise
A * B

ValueError: ignored

In [0]:
C = np.matmul(A, B)
print(C)

[[0.49051016 0.42626899 0.14236231 0.50317482 0.59031338 0.18438825]
 [1.7561817  0.78903062 0.411984   1.26831541 0.95510342 0.98785419]
 [1.51168789 0.68529337 0.50457281 1.17365806 0.78946757 0.81579948]]


In [0]:
# Remember how matrix multiplication works. 
C = np.matmul(B, A)

ValueError: ignored

For one dimensional arrays, indexing, slicing and iterating work the same way as in Python lists. For arrays with more than one dimension (axis) there is one index per axis separated by commas.

In [0]:
c = np.array([[0,1,2,3,4], [5,6,7,8,9],[10,11,12,13,14], [15,16,17,18,19], [20,21,22,23,24],[25,26,27,28,29]])
print(c)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [0]:
c[3,2]

17

In [0]:
# Numpy supports slicing
c[1:3, 2:4]

array([[ 7,  8],
       [12, 13]])

In [0]:
# Second column
c[:,2]

array([ 2,  7, 12, 17, 22, 27])

In [0]:
# Last 3 columns
c[:,2:]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19],
       [22, 23, 24],
       [27, 28, 29]])

In [0]:
# Third row
c[2,:]

array([10, 11, 12, 13, 14])

In [0]:
# This will be interpreted as c[2,:]
c[2]

array([10, 11, 12, 13, 14])

In [0]:
d = np.array([[[1,2,3],
               [4,5,6]],
              [[7,8,9],
               [10,11,12]]])

In [0]:
d.shape

(2, 2, 3)

In [0]:
# Front face
d[:,:,0]

array([[ 1,  4],
       [ 7, 10]])

In [0]:
# Midlayer
d[:,:,1]

array([[ 2,  5],
       [ 8, 11]])

In [0]:
#Back face
d[:,:,2]

array([[ 3,  6],
       [ 9, 12]])

In [0]:
d[0,1,:]

array([4, 5, 6])

# Broadcasting

The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. 

NumPy operations are usually done on pairs of arrays on an element-by-element basis. In the simplest case, the two arrays must have exactly the same shape, as in the following example:

In [0]:
a = np.array([1,2,3])
b = np.array([5,5,5])
a*b

array([ 5, 10, 15])

NumPy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints. The simplest broadcasting example occurs when an array and a scalar value are combined in an operation:

In [0]:
c = 5
a * c

array([ 5, 10, 15])

The result is equivalent to the previous example where b was an array. We can think of the scalar b being stretched during the arithmetic operation into an array with the same shape as a. The new elements in b are simply copies of the original scalar. The stretching analogy is only conceptual. NumPy is smart enough to use the original scalar value without actually making copies, so that broadcasting operations are as memory and computationally efficient as possible.

The first rule of broadcasting is that if all input arrays do not have the same number of dimensions, a “1” will be repeatedly prepended to the shapes of the smaller arrays until all the arrays have the same number of dimensions.

The second rule of broadcasting ensures that arrays with a size of 1 along a particular dimension act as if they had the size of the array with the largest shape along that dimension. The value of the array element is assumed to be the same along that dimension for the “broadcast” array.

In [0]:
d = np.array([[[1,2,3],
               [4,5,6]],
              [[7,8,9],
               [10,11,12]]])
print(d.shape)
scale = np.array([1,2,3])
print(scale.shape)

(2, 2, 3)
(3,)


In [0]:
d * scale

array([[[ 1,  4,  9],
        [ 4, 10, 18]],

       [[ 7, 16, 27],
        [10, 22, 36]]])

In [0]:
scale2 = np.array([[1],[2]])
scale2.shape

If we try `d*scale2`, then `scale2` will brodcast to the following 

      ```
      [[[1,1,1],
        [2,2,2]], 
       [[1,1,1],
        [2,2,2]]]
       ```

In [0]:
d*scale2

# Index arrays

NumPy arrays may be indexed with other arrays.

In [0]:
arr = np.array([1,2,3,4,5,6,7,8,9])

In [0]:
arr[[1,1,3,-1]] 

array([2, 2, 4, 9])

In [0]:
arr[np.array(range(0,10,2))]

array([1, 3, 5, 7, 9])

## Boolean or “mask” index arrays

Boolean arrays can be used as index for arrays. The result is an array containing all the elements in the indexed array corresponding to all the true elements in the boolean array. 

In [0]:
# Create an array of 1000 random integers chosen from a discrete uniform distribution over {0,1,...,9}
arr2 = np.random.randint(0,10,1000)
print(arr2)

[7 0 6 3 3 2 6 0 9 3 4 6 9 6 4 2 1 1 3 1 4 3 3 7 4 8 7 2 3 5 0 6 5 8 7 0 0
 9 6 9 9 3 7 0 7 2 5 8 7 8 3 4 3 2 8 1 4 3 1 9 9 4 9 2 8 0 8 5 8 6 5 2 2 2
 2 7 1 6 6 9 4 0 3 7 0 1 5 9 8 9 4 9 8 5 1 1 0 0 3 5 7 1 7 4 6 2 3 4 2 5 9
 8 4 3 1 6 6 0 3 8 5 0 2 2 2 2 4 6 2 4 3 6 1 9 4 7 0 0 0 2 0 8 9 0 1 1 6 4
 1 0 5 6 6 7 4 0 9 8 0 7 9 7 3 5 7 2 1 3 9 2 6 2 7 1 9 2 3 6 7 1 4 3 6 1 7
 5 2 2 6 5 3 0 3 0 0 8 3 3 2 8 2 9 5 6 4 5 0 7 5 6 4 1 8 6 1 8 8 9 1 8 8 8
 1 2 7 9 2 6 8 8 7 8 8 7 0 9 7 0 6 0 8 6 6 4 6 6 3 3 2 2 2 3 8 9 8 5 6 7 3
 1 4 4 0 3 7 7 8 5 8 0 4 2 3 7 1 7 0 2 6 0 8 8 4 8 1 3 9 5 4 4 9 7 4 2 9 7
 7 5 9 3 7 8 4 7 4 9 3 5 8 7 8 1 7 2 6 3 7 9 4 5 1 8 2 3 8 7 5 1 5 7 9 8 8
 1 6 5 4 8 4 2 5 7 2 3 0 2 4 2 0 6 1 8 4 5 5 5 7 9 1 9 4 7 4 2 4 8 3 2 1 1
 1 7 4 4 4 6 6 1 1 1 0 6 9 1 4 5 1 6 4 2 5 2 0 0 0 4 8 1 4 3 0 9 9 7 8 5 2
 1 8 2 9 7 3 9 7 3 9 4 9 6 9 2 3 4 2 2 5 1 2 0 1 2 6 3 8 8 3 5 9 9 4 2 3 8
 1 3 2 6 1 5 8 4 0 4 8 2 3 2 3 1 9 5 9 2 3 1 9 3 2 0 0 0 0 8 9 2 7 5 4 8 4
 1 4 2 7 3 8 8 7 1 4 5 4 

In [0]:
# Get all the elements in the array that are less than 5
mask = arr2 < 5
arr2[mask]

array([0, 3, 3, 2, 0, 3, 4, 4, 2, 1, 1, 3, 1, 4, 3, 3, 4, 2, 3, 0, 0, 0,
       3, 0, 2, 3, 4, 3, 2, 1, 4, 3, 1, 4, 2, 0, 2, 2, 2, 2, 1, 4, 0, 3,
       0, 1, 4, 1, 1, 0, 0, 3, 1, 4, 2, 3, 4, 2, 4, 3, 1, 0, 3, 0, 2, 2,
       2, 2, 4, 2, 4, 3, 1, 4, 0, 0, 0, 2, 0, 0, 1, 1, 4, 1, 0, 4, 0, 0,
       3, 2, 1, 3, 2, 2, 1, 2, 3, 1, 4, 3, 1, 2, 2, 3, 0, 3, 0, 0, 3, 3,
       2, 2, 4, 0, 4, 1, 1, 1, 1, 2, 2, 0, 0, 0, 4, 3, 3, 2, 2, 2, 3, 3,
       1, 4, 4, 0, 3, 0, 4, 2, 3, 1, 0, 2, 0, 4, 1, 3, 4, 4, 4, 2, 3, 4,
       4, 3, 1, 2, 3, 4, 1, 2, 3, 1, 1, 4, 4, 2, 2, 3, 0, 2, 4, 2, 0, 1,
       4, 1, 4, 4, 2, 4, 3, 2, 1, 1, 1, 4, 4, 4, 1, 1, 1, 0, 1, 4, 1, 4,
       2, 2, 0, 0, 0, 4, 1, 4, 3, 0, 2, 1, 2, 3, 3, 4, 2, 3, 4, 2, 2, 1,
       2, 0, 1, 2, 3, 3, 4, 2, 3, 1, 3, 2, 1, 4, 0, 4, 2, 3, 2, 3, 1, 2,
       3, 1, 3, 2, 0, 0, 0, 0, 2, 4, 4, 1, 4, 2, 3, 1, 4, 4, 3, 4, 1, 1,
       3, 2, 2, 1, 0, 0, 1, 4, 2, 4, 1, 0, 4, 3, 0, 2, 2, 0, 1, 2, 0, 3,
       2, 3, 1, 1, 4, 2, 3, 0, 0, 4, 0, 3, 0, 4, 2,

In [0]:
len(arr2[mask])

503

In [0]:
# Get all the even elements in the array
even = arr2[arr2 % 2 == 0]
even

array([0, 6, 2, 6, 0, 4, 6, 6, 4, 2, 4, 4, 8, 2, 0, 6, 8, 0, 0, 6, 0, 2,
       8, 8, 4, 2, 8, 4, 4, 2, 8, 0, 8, 8, 6, 2, 2, 2, 2, 6, 6, 4, 0, 0,
       8, 4, 8, 0, 0, 4, 6, 2, 4, 2, 8, 4, 6, 6, 0, 8, 0, 2, 2, 2, 2, 4,
       6, 2, 4, 6, 4, 0, 0, 0, 2, 0, 8, 0, 6, 4, 0, 6, 6, 4, 0, 8, 0, 2,
       2, 6, 2, 2, 6, 4, 6, 2, 2, 6, 0, 0, 0, 8, 2, 8, 2, 6, 4, 0, 6, 4,
       8, 6, 8, 8, 8, 8, 8, 2, 2, 6, 8, 8, 8, 8, 0, 0, 6, 0, 8, 6, 6, 4,
       6, 6, 2, 2, 2, 8, 8, 6, 4, 4, 0, 8, 8, 0, 4, 2, 0, 2, 6, 0, 8, 8,
       4, 8, 4, 4, 4, 2, 8, 4, 4, 8, 8, 2, 6, 4, 8, 2, 8, 8, 8, 6, 4, 8,
       4, 2, 2, 0, 2, 4, 2, 0, 6, 8, 4, 4, 4, 2, 4, 8, 2, 4, 4, 4, 6, 6,
       0, 6, 4, 6, 4, 2, 2, 0, 0, 0, 4, 8, 4, 0, 8, 2, 8, 2, 4, 6, 2, 4,
       2, 2, 2, 0, 2, 6, 8, 8, 4, 2, 8, 2, 6, 8, 4, 0, 4, 8, 2, 2, 2, 2,
       0, 0, 0, 0, 8, 2, 4, 8, 4, 4, 2, 8, 8, 4, 4, 4, 6, 6, 2, 2, 8, 0,
       8, 0, 4, 2, 8, 8, 4, 8, 6, 6, 6, 0, 4, 6, 8, 0, 2, 2, 0, 6, 2, 8,
       0, 8, 2, 4, 2, 6, 6, 0, 0, 8, 6, 4, 0, 0, 4,

In [0]:
len(even)

521

In [0]:
# Find the relative frequency of each element in the array. 
for i in range(10):
    print("Relative frequency of {} is {}".format(i,len(arr2[arr2 == i])/ 1000))

Relative frequency of 0 is 0.097
Relative frequency of 1 is 0.095
Relative frequency of 2 is 0.111
Relative frequency of 3 is 0.092
Relative frequency of 4 is 0.108
Relative frequency of 5 is 0.091
Relative frequency of 6 is 0.101
Relative frequency of 7 is 0.11
Relative frequency of 8 is 0.104
Relative frequency of 9 is 0.091


This concludes our introduction to Numpy. We have only scratched the surface. We will explain further notions as needed. For more details on Numpy see the [user guide](https://docs.scipy.org/doc/numpy/user/).

# Tensorflow

Tensorflow is an open-source python library for machine learning developed by Google. 
In the rest of this notebook, we will be introducing basic concepts in Tensorflow's low level API. We will be working in Tensorflow 2.0.
At the time of writing this notebook, the default version installed in google colab is Tensorflow 1.14. So we need to manually select Tensorflow 2.0 before we import. 

In [0]:
%tensorflow_version 2.x

Check the tensorflow version using the code below.

In [0]:
import tensorflow as tf
print(tf.__version__)

2.1.0-rc1


## Tensorflow Low Level API

In most of the projects in this course you will be using tensorflow high level API, Keras. However, in order to have a better understanding of tensorflow it is important to know a little bit about the low level objects in tensorflow. These concepts will be useful if you want to write custom loss functions, layers, regularizers, initializers and so on. 

## Tensors

Tensors are the main objects that tensorflow operates on. They are generalizations of matrices to higher dimensional arrays just like numpy arrays. Think of tensors as n-dimensional arrays. 

In [0]:
# A constant tensor with value 5
a = tf.constant(5)

In [0]:
a

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [0]:
# A multidimensional tensor
b = tf.constant([[1,2,3,4], [5,6,7,8]])

In [0]:
b

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int32)>

In [0]:
# You can turn tensors into numpy arrays by `numpy()` method.
b.numpy()

array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int32)

## Gradient tape

Tensorflow provides the class `GradientTape` that perform automatic differentiation. It is used together with Python `with` keyword. The line `with tf.GradientTape() as tape` creates a GradientTape object named as 'tape' and this object keeps track of the operations performed on the tensors that it watches. In this example, the tape watches only a single tensor `x`. Then the `gradient` method returns the derivative of the tensor `square` with respect to `x` evaluated at the value of `x`. 

In [0]:
x = tf.constant(5.0)
with tf.GradientTape() as tape:
    #Make the tape watch the tensor x. Because of this line the tape will keep
    #track of all operations involving x and use this to find the derivative 
    #of any variable defined as a differentiable function of x.
    tape.watch(x)
    square = x*x
derivative = tape.gradient(square, x)

In [0]:
print(derivative)

tf.Tensor(10.0, shape=(), dtype=float32)
